it_analysis_data_prep.py:
    #the sources to be analyzed
    srcs: 
        - 'discharge'
        - 'specific_conductance'
        - 'prcp'
        - 'tmax'
        - 'tmin'
        - 'wspdir'
    #the sinks to be analyzed, this will likely be the salt front location
    snks:
        - 'saltfront_daily'
        - 'saltfront7_weekly'
    preprocess_steps:
        mutual_information:
            sources:
                prcp:
                    - remove_seasonal_signal
                    - normalize
                tmax:
                    - remove_seasonal_signal
                    - normalize
                tmin:
                    - remove_seasonal_signal
                    - normalize
                wspdir:
                    - remove_seasonal_signal
                    - normalize               
                discharge:
                    - remove_seasonal_signal
                    - normalize
                specific_conductance:
                    - remove_seasonal_signal
                    - normalize
            sinks:
                saltfront:
                    - remove_seasonal_signal
                    - normalize
                saltfront7:
                    - remove_seasonal_signal
                    - normalize

        correlation:
            sources:
                prcp:
                    - none
                tmax:
                    - none
                tmin:
                    - none
                wspdir:
                    - none
                discharge:
                    - none
                specific_conductance:
                    - none
            sinks:
                saltfront:
                    - none
                saltfront7:
                    - none
    #date range of interest
    date_start: '2000-01-01'
    date_end: '2019-12-31'
    #number of lags to analyze
    n_lags: 0
    #where to write the sinks and lagged sources as binary pickle files
    out_dir: '03_it_analysis/out/'
    #should preprocessing plots be saved
    plot: True
    
    