it_analysis_data_prep.py:
    #the sources to be analyzed
    srcs: 
        - 'discharge'
        - 'specific_conductance'
    #the sinks to be analyzed, this will likely be the salt front location
    snks:
        - 'Daily_River_Mile_Corrected'
        - 'Corrected_7d_average'
    #date range of interest
    date_start: '2019-06-01'
    date_end: '2019-12-31'
    #number of lags to analyze
    n_lags: 4
    #where to write the sinks and lagged sources as binary pickle files
    out_dir: '03_it_analysis/out/'
    