plot_heat_map.py:
    #matrix to plot
    matrix: '03_it_analysis/out/corr_matrix'
    #mask threshold
    mask_threshold: 0.25
    #dates for analysis
    date_start: '01-01-2019'
    date_end: '12-31-2019'
    #save location
    save_location: '03_it_analysis/out/correlation_heatmap.png'
    #save? true/false
    save: True
