#location of data release
sb_url: 'https://www.sciencebase.gov/catalog/file/get/5f6a289982ce38aaa2449135?f=__disk__a6%2Fb3%2Ffb%2Fa6b3fb14393cb6b83d25897b395a92c4f4a193ed'
#data file
prms_predictions: 'sntemp_inputs_outputs_drb'
#destination to write
destination: '02_munge/in/'

# define crosswalk between nwis site and sntemp data
# 'nwis_site': sntemp_seg_id_nat
fill_segments:
  # trenton
  '01463500': 1498
  # schuylkill
  '01474500': 2338
