# choose where you want to read your data inputs from: local or S3
read_location: 'S3'
# choose where you want to write your data outputs: local or S3
write_location: 'local'
# set name of AWS profile storing credentials for S3
aws_profile: 'dev'
# set AWS bucket to read/write to
s3_bucket: 'drb-estuary-salinity'

#location of new netcdf with subsetted data
netcdf_path: f'./01_munge/out/coawst_salt_only_2019.nc'
