name: drb_estuary_salinity
channels:
  - defaults
  - bioconda
  - pytorch
  - plotly
  - conda-forge
<<<<<<< HEAD
  - pypi
=======
>>>>>>> bc79a579525dc0c959fb9f39c86213e480f831c2
dependencies:
  - numpy
  - pandas
  - python=3.8
  - joblib
  - matplotlib
  - yaml
  - boto3
  - tqdm
  - snakemake-minimal
  - ca-certificates
  - certifi
  - openssl
  - xarray
  - torchvision
  - pytorch
  - cudatoolkit=10.2
  - torchaudio
  - ipympl
  - plotly=5.5.0
  - spyder
  - scipy
  - zarr
  - lz4
  - seaborn
  - dask
  - scikit-learn
  - pip=21.2.2
  - pip:
      - sciencebasepy


