plot_heatmap.py:
    #matrix to plot
    mi_matrix: '03a_it_analysis/out/mi_matrix'
    corr_matrix: '03a_it_analysis/out/corr_matrix'
    #mask threshold mutual information
    mask_threshold_mi: 0.01
    #mask threshold correlation
    mask_threshold_corr: 0.05
    #save location
    save_location: '03a_it_analysis/out/'
    #save? true/false
    save: True
