fetch_usgs_sites:
  site_ids:
    #- '01411390' # Cape May Harbor at Cape May NJ
    - '01463500' # Delaware River at Trenton NJ
    #- '01464040' # Delaware River at Marine Terminal at Trenton NJ
    #- '014670261' # Delaware River at Pennypack Woods PA
    #- '01467059' # Delaware River at Riverton NJ
    #- '01467200' # Delaware River at Penn's Landing, Philadelphia, PA
    - '01474500' # Schuylkill River at Philadelphia, PA
    #- '01474703' # Delaware River at Fort Mifflin at Philadelphia, PA
    #- '01477050' # DELAWARE RIVER AT CHESTER PA
    #- '01482695' # C AND D CANAL NR DELAWARE CITY, DE
    #- '01482800' # Delaware River at Reedy Island Jetty, DE

fetch_noaa_nos_sites:
  station_ids:
  - '8536110' # Cape May
  - '8557380' # Lewes
  #- '8548989' # Newbold, PA
  #- '8539094' # Burlington, NJ
  #- '8546252' # Bridesburg, NJ
  - '8545240' # Philadelphia, PA
  #- '8540433' # Marcus Hook, PA
  #- '8551762' # Delaware City, DE
  - '8551910' # Reedy Point, DE
  #- '8537121' # Ship John Shoal, NJ
  - '8555889' # Brandywine Shoal Lighthouse, DE
