fetch_usgs.py:
  # choose where you want to write your data outputs: local or S3
  write_location: 'local'
  # set name of AWS profile storing credentials for S3
  aws_profile: 'dev'
  # set AWS bucket to read/write to
  s3_bucket: 'drb-estuary-salinity'

  # usgs nwis sites we want to fetch data for
  site_ids:
    #- '01411390' # Cape May Harbor at Cape May NJ
    - '01463500' # Delaware River at Trenton NJ
    #- '01464040' # Delaware River at Marine Terminal at Trenton NJ
    #- '014670261' # Delaware River at Pennypack Woods PA
    #- '01467059' # Delaware River at Riverton NJ
    #- '01467200' # Delaware River at Penn's Landing, Philadelphia, PA
    - '01474500' # Schuylkill River at Philadelphia, PA
    #- '01474703' # Delaware River at Fort Mifflin at Philadelphia, PA
    #- '01477050' # DELAWARE RIVER AT CHESTER PA
    #- '01482695' # C AND D CANAL NR DELAWARE CITY, DE
    #- '01482800' # Delaware River at Reedy Island Jetty, DE
 
  # start and end dates for data fetch
  # should be in the format 'YYYY-MM-DD'
  start_dt: '2000-01-01'
  end_dt: '2019-12-31'

fetch_noaa_nos.py:
  #choose where you want to write your data outputs: local or S3
  write_location: 'local'
  #set name of AWS profile storing credentials for S3
  aws_profile: 'dev'
  #set AWS bucket to read/write to
  s3_bucket: 'drb-estuary-salinity'

  station_ids:
  - '8536110' # Cape May
  - '8557380' # Lewes
  #- '8548989' # Newbold, PA
  #- '8539094' # Burlington, NJ
  #- '8546252' # Bridesburg, NJ
  - '8545240' # Philadelphia, PA
  #- '8540433' # Marcus Hook, PA
  #- '8551762' # Delaware City, DE
  - '8551910' # Reedy Point, DE
  #- '8537121' # Ship John Shoal, NJ
  - '8555889' # Brandywine Shoal Lighthouse, DE

  # options:
  # HAT: Highest Astronomical Tide
  # MHHW: Mean Higher High Water
  # MHW: Mean High Water
  # DTL: Diurnal Tide Level
  # MTL: Mean Tide Level
  # MSL: Mean Sea Level
  # MLW: Mean Low Water
  # MLLW: Mean Lower Low Water
  # LAT: Lowest Astronomical Tide
  # GT: Great Diurnal Range
  # MN: Mean Diurnal Range
  # DHQ: Mean Diurnal High Water Inequality
  # HWI: Greenwich High Water Interval
  # LWI: Greenwich Low Water Interval
  # Max Tide: Highest Observed Tide
  # Min Tide: Lowest Observed Tide
  # Station Datum: fixed base elevation at a tide station
  # National Tidal Datum Epoch: The specific 19-year period adopted by the National Ocean Service as the official time
  # segment over which tide observations are taken and reduced to obtain mean values (e.g., mean lower low water, etc.) for tidal datums.
  datum: 'MSL'

  # options: water_level, air_temperature, water_temperature, wind, air_pressure, air_gap, conductivity, visibility,
  # humidity, salinity, hourly_height, high_low, daily_mean, monthly_mean, one_minute_water_level, predictions, datums,
  # currents, and currents_predictions.
  products: 
      - 'water_level'
      - 'conductivity'
      - 'predictions'
      - 'air_pressure'
      #- 'air_temperature'

  # options:
  # gmt: Greenwich Mean Time
  # lst: Local Standard Time. The time local to the requested station.
  # lst_ldt: Local Standard/Local Daylight Time. The time local to the requested station.
  time_zone: 'GMT'

  # options: english and metric
  units: 'metric'

  # options: csv, json, xml
  file_format: 'json'


  start_year: '2000'
  end_year: '2019'
  start_dt: '20190101'
  end_dt: '20191231'
  
fetch_COAWST_model.py:
  #choose where you want to write your data outputs: local or S3
  write_location: 'local'
  #set name of AWS profile storing credentials for S3
  aws_profile: 'dev'
  #set AWS bucket to read/write to
  s3_bucket: 'drb-estuary-salinity'
  #set up AWS client
  s3_client: utils.prep_write_location(write_location, aws_profile)
  
  #select COAWST model run
  url: 'http://geoport.whoi.edu/thredds/dodsC/vortexfs1/usgs/users/scook/proj/DE_Bay/run07/run07C/ocean_deb_his_run07C_tsvar_00010.nc'
  # Other model run options:
  # Model Output with Subtidal Signal
  # url: https://geoport.whoi.edu/thredds/catalog/vortexfs1/usgs/users/scook/proj/DE_Bay/run07/run07C/run07C_tide_subtidal/ocean_deb_his_run07C_tsvar_00010.
  # Model Output with Waves - 
  # url: https://geoport.whoi.edu/thredds/catalog/vortexfs1/usgs/users/scook/proj/DE_Bay/run07/run07C/run07C_waves/era5_2019/catalog.html?  dataset=vortexfs1/usgs/users/scook/proj/DE_Bay/run07/run07C/run07C_waves/era5_2019/ocean_deb_his_run07C_waves_tsvar_2019_00012.nc
  
  river_mile_coords_filepath: '/01_fetch/src/river_mile_coords.csv'
  
  model_run: 'only'
  # model runs: 'waves', 'subtidal_signal'
  
  model_run_year: '2019'
