#choose where you want to write your data outputs: local or S3
write_location: 'local'
#set name of AWS profile storing credentials for S3
aws_profile: 'dev'
#set AWS bucket to read/write to
s3_bucket: 'drb-estuary-salinity'

# variables:
# 'ATemp', 'F_ATemp', 'RH', 'BP', 'WSpd', 'MaxWSpd',
# 'MaxWSpdT', 'Wdir', 'SDWDir', 'TotPAR',
# 'TotPrcp', 'TotSoRad', 
vars: ['ATemp', 'BP', 'WSpd', 'Wdir', 'TotPrcp']