#choose where you want to read your data inputs from: local or S3
read_location: 'local'
#choose where you want to write your data outputs: local or S3
write_location: 'local'
#set name of AWS profile storing credentials for S3
aws_profile: 'dev'
#set AWS bucket to read/write to
s3_bucket: 'drb-estuary-salinity'

# create a mapping of which site data is contained 
# in which zip folder
zip_folders: {'delsjmet': '953860'}